name: cupertino_page_controller
description: allow to check current page in list
version: 0.0.2
repository: https://github.com/Antoinegtir/cupertino-page-control
homepage: https://github.com/Antoinegtir/cupertino-page-control
View/report issues: https://github.com/Antoinegtir/cupertino-page-control/issues
contributing: https://github.com/Antoinegtir/cupertino-page-control/blob/main/CONTRIBUTING.md

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
